### ISSUE TITLE
Alien4cloud doesn't support empty string for default value in property definition for node type

### ISSUE THREAD

**Issue by stebenoist** [alien4cloud/alien4cloud#169]
For a string-typed property defined in a node type as by instance:
```
node_types:
  my_company.my_types.MyAppNodeType:
    derived_from: tosca.nodes.SoftwareComponent
    description: My company’s custom applicaton
    properties:
      my_empty_default_prop:
        type: string
        description: "a prop with an empty string as default value"
        default: ""
```
The yaml parsing removes the default with empty string.
