### ISSUE TITLE
CSAR parse sets up relationships before inherited requirements of local types (and so fails)

### ISSUE THREAD

**Issue by ahgittin** [alien4cloud/alien4cloud#68]
i upload a CSAR which defines a node type B (say `my.Software`) which is derived from pre-loaded type A (say `tosca.nodes.SoftwareComponent`), and a topology template with a node template of type B using a requirement from A (say `host`).  the parsing fails complaining that `REQUIREMENT_NOT_FOUND`.

it looks like `derived_from` requirements are not loaded until the archive index / merge, but the requirement validation and relationship construction are made before that.

Example:

```
node_types:
  my.Software:
      derived_from: tosca.nodes.SoftwareComponent
      abstract: true

topology_template:
  node_templates:
    my_software:
      type: my.Software
      requirements:
      - host: a_server
        
    a_server:
      type: tosca.nodes.Compute
```
