### ISSUE TITLE
Assign values to topology's input

### ISSUE THREAD

**Issue by kiuby88** [alien4cloud/alien4cloud#79]
Hi all

How can I add a value to a topology input un a template? For example,  [this template](https://github.com/alien4cloud/alien4cloud/blob/d802eef4cc3cd7416155d4716ecb79e1de861dd8/alien4cloud-rest-it/src/test/resources/data/csars/topology_template/topology-substitution/service-template.yml) contains a NodeTemplates `mysql` which assigns several inputs as properties values, such as:
```
properties:
        db_port: { get_input: db_port }
        db_name: { get_input: db_name }
        db_user: { get_input: db_user }
        db_password: { get_input: db_password }
``` 

But, how can I assign some values to the topology inputs? For example, I'd like to assign `admin` value to `db_user` input. I have reviewed the project's yamls but I did not find an example about this.

Thanks a lot.
