### ISSUE TITLE
Properties for Relationships

### ISSUE THREAD

**Issue by kiuby88** [alien4cloud/alien4cloud#81]
Hi all

I am trying to add some properties to a requirement/relation.
I am using the following template

```
tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03

imports:
  - tosca-normative-types:1.0.0.wd03-SNAPSHOT

template_name: simple.chatApplication
template_version: 1.0.0-SNAPSHOT

description: HelloWorld application. (ChatApplication)

relationship_types:
  tosca.relationships.Configure:
    derived_from: tosca.relationships.DependsOn
    valid_targets: [ tosca.capabilities.Endpoint ]
    properties:
      prop.name:
        type: string
        required: false
      prop.value:
        type: string
        required: true
      prop.collection:
        type: string
        required: false
        
node_types:
  tomcat.TomcatServer:
    derived_from: tosca.nodes.Root
    description: >
      A simple Tomcat server
    properties:
      wars.root:
        type: string
        required: false
      http.port:
        type: list
        required: false
        entry_schema:
          type: string
      java.sysprops:
        type: map
        required: false
        entry_schema:
          type: string
    requirements:
      - dbConnection: tosca.nodes.Root
        type: tosca.relationships.Configure

  mysql.MySqlNode:
    derived_from: tosca.nodes.Root
    description: >
      A MySQL server
    properties:
      "datastore.creation.script.url":
        type: string
        required: false
    capabilities:
      dbConnection: tosca.capabilities.DatabaseEndpoint


topology_template:
  description: Web Server Sample with Script
  node_templates:
    tomcat_server:
      type: tomcat.TomcatServer
      properties:
        wars.root: "http://hello-world-sql-webapp-0.6.0.war"
        http.port: "8080+"
      requirements:
        - dbConnection: mysql_server
          relationship_type: tosca.relationships.Configure
          properties:
            prop.collection: java.sysprops
            prop.name: example.db.url
            prop.vale: value

    mysql_server:
      type: mysql.MySqlNode
      properties:
        datastore.creation.script.url: "https://visitors-creation-script.sql"
```

However, the `tomcat_server.dbConnection` requirement does not contain any property.  The relationship used by this requirement contains three properties but their values are always null.
I have tried to use a `relationship_template`
```
relationship_templates:
  database_connection:
    type: tosca.relationships.Configure
    properties:
      prop.collection: java.sysprops
      prop.name: brooklyn.example.db.url
      prop.vale: value
```
But I obtained the same result.
I tried to define the properties on the requirement definition (TomcatServer NodeTemplate) but I obtained the same result again, three properties (`prop.collection`, `prop.name` and `prop.value`) with null values.

```
node_types:
  tomcat.TomcatServer:
    derived_from: tosca.nodes.Root
    description: >
      A simple Tomcat server
    properties:
    ...
    requirements:
      - dbConnection: tosca.nodes.Root
        type: tosca.relationships.Configure
        properties:
          prop.name:
            type: string
            required: false
          prop.value:
            ...
          prop.collection:
            ...
```
       
I am sure that it is my fault but I do not find the problem.
WDYT?

**Comment by igorng** [comment]
Hello,
Currently we do not support the parsing of relationship's properties when importing a yaml topology.
I invite you to create an issue for that.

This said, notice that the alien4cloud ui allows you to set and use those relationships properties.

HTH :)

**Comment by igorng** [comment]
Oh my bad, I think I was wrong!
Actually parsing relationships properties is indeed supported (in the latest alien4cloud version, that is 1.1.0-SM26). After a deep debuging, found that your definition in **requirements** part is wrong. You should do:
```yaml
      requirements:
        - dbConnection: 
            node: mysql_server
            relationship: tosca.relationships.Configure
            properties:
              prop.collection: java.sysprops
              prop.name: example.db.url
              prop.value: value
```
instead of
```yaml
      requirements:
        - dbConnection: mysql_server
          relationship_type: tosca.relationships.Configure
          properties:
            prop.collection: java.sysprops
            prop.name: example.db.url
            prop.vale: value
```
Might be good to mention that the short syntax is also valid:
```yaml
      requirements:
        - dbConnection: mysql_server
```
Notice that there is nothing else defined after *- dbConnection: mysql_server*, therefore, it can not be used if you want to specify more than just the name of the target node.

Sorry again, and let us know if the porblem is solved.

Thanks.
